config/routes.rb
MealClub::Application.routes.draw do |map|
  resources :meals do
    resources :cooks
	resources :guests
  end

  root :to => "home#index"

end

app/models/meal.rb
class Meal < ActiveRecord::Base
  validates_numericality_of :cost, :on => :create
  has_many :meal_cooks
  has_many :meal_guests
  has_many :cooks, :through => :meal_cooks, :source => :member
  has_many :guests, :through => :meal_guests, :source => :member
end

app/models/meal_cook.rb
class MealCook < ActiveRecord::Base
  belongs_to :meal
  belongs_to :member
end

app/models/meal_guest.rb
class MealGuest < ActiveRecord::Base
  belongs_to :meal
  belongs_to :member
end

app/models/member.rb
class Member < ActiveRecord::Base
  has_many :meal_cooks
  has_many :meal_guests
  has_many :meals_cooked, :through => :meal_cooks, :source => :meal
  has_many :meals_as_guest, :through => :meal_guests, :source => :meal
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  layout 'application'
end

app/controllers/cooks_controller.rb
class CooksController < ApplicationController
  def create
    @meal = Meal.find(params[:meal_id])
    @member = Member.first(:conditions => ["name = ?", params[:cook][:name]])
    if not @member
      @member = Member.new
      @member.name = params[:cook][:name]
      @member.save
    end
    
    @cook = @meal.meal_cooks.create
    @cook.meal = @meal
    @cook.member = @member

    respond_to do |format|
      if @cook.save
        format.html { redirect_to(@meal, :notice => 'Cook was successfully created.') }
        format.xml  { render :xml => @meal, :status => :created, :location => @meal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @meal.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def create
    @meal = Meal.find(params[:meal_id])
    @member = Member.first(:conditions => ["name = ?", params[:guest][:name]])
    if not @member
      @member = Member.new
      @member.name = params[:guest][:name]
      @member.save
    end
    
    @guest = @meal.meal_guests.create
    @guest.meal = @meal
    @guest.member = @member

    respond_to do |format|
      if @guest.save
        format.html { redirect_to(@meal, :notice => 'Guest was successfully created.') }
        format.xml  { render :xml => @meal, :status => :created, :location => @meal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @meal.errors, :status => :unprocessable_entity }
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  # GET /meals
  # GET /meals.xml
  def index
    @meals = Meal.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @meals }
    end
  end

  # GET /meals/1
  # GET /meals/1.xml
  def show
    @meal = Meal.find(params[:id])
    @new_cook = @meal.cooks.build
    @new_guest = @meal.guests.build

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @meal }
    end
  end

  # GET /meals/new
  # GET /meals/new.xml
  def new
    @meal = Meal.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @meal }
    end
  end

  # GET /meals/1/edit
  def edit
    @meal = Meal.find(params[:id])
  end

  # POST /meals
  # POST /meals.xml
  def create
    @meal = Meal.new(params[:meal])

    respond_to do |format|
      if @meal.save
        format.html { redirect_to(@meal, :notice => 'Meal was successfully created.') }
        format.xml  { render :xml => @meal, :status => :created, :location => @meal }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @meal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /meals/1
  # PUT /meals/1.xml
  def update
    @meal = Meal.find(params[:id])

    respond_to do |format|
      if @meal.update_attributes(params[:meal])
        format.html { redirect_to(@meal, :notice => 'Meal was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @meal.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.xml
  def destroy
    @meal = Meal.find(params[:id])
    @meal.destroy

    respond_to do |format|
      format.html { redirect_to(meals_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cooks_helper.rb
module CooksHelper
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/home/index.html.erb
<h1>Welcome to MealClub!</h1>
<%= link_to "Meal List", meals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MealClub</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meals/_form.html.erb
<%= form_for(@meal) do |f| %>
  <% if @meal.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>
    <ul>
    <% @meal.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :cost %><br />
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<h1>Listing meals</h1>

<table>
  <tr>
    <th>Date</th>
    <th>Cost</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meals.each do |meal| %>
  <tr>
    <td><%= meal.date.strftime("%A %d %B %Y") if (!meal.date.nil?) %></td>
    <td><%= "€%.2f" % meal.cost %></td>
    <td><%= meal.description %></td>
    <td><%= link_to 'Show', meal %></td>
    <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
    <td><%= link_to 'Destroy', meal, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/show.html.erb
<p class="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @meal.date.strftime("%A %d %B %Y") if (!@meal.date.nil?) %>
</p>

<p>
  <b>Cost:</b>
  <%= "€%.2f" % @meal.cost %>
</p>

<p>
  <b>Description:</b>
  <%= @meal.description %>
</p>

<h2>Cooks</h2>
<% @meal.cooks.each do |cook| %>
<p>
	<b>Cook:</b>  <%= cook.name %>
</p>
<% end %> 

<h2>Add a cook:</h2>

<%= form_for :cook, @new_cook, :url => meal_cooks_path(@meal) do |f| %>
	<%= f.error_messages %>
	<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
	</div>
	<div class="actions">
	<%= f.submit %>
	</div>
<% end %> 

<h2>Guests</h2>
<% @meal.guests.each do |guest| %>
<p>
	<b>Guest:</b>  <%= guest.name %>
</p>
<% end %>

<h2>Add a guest:</h2>

<%= form_for :guest, @new_guest, :url => meal_guests_path(@meal) do |f| %>
	<%= f.error_messages %>
	<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
	</div>
	<div class="actions">
	<%= f.submit %>
	</div>
<% end %>

<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %>